export var primary = "#3EA8DD"
export var secondary = "#3EA8DD"
export var tertiary = "#3EA8DD"
export var success = "#52C1A3"
export var warning = "#FCA360"
export var danger = "#F76E5C"
export var neutralCool = "#696E7B"
export var neutral = "#68665E"